### ISSUE TITLE
Transfer of funds.

### ISSUE THREAD

**Issue by ToadTime** [garnettjolissainttgu/stellar-wallet#1]
When I try to send funds out of the Stellar Wallet it says there's a problem try again later... I have tried all day and with a couple different wallets and nothing is working.

**Comment by ToadTime** [comment]
I solved my issue I know how to fix this but this app is worthless it says earn free xlm upon using the wallet I never received any free xlm and you can't send xlm to anything else it's a broken wallet.

**Comment by TomGill83** [comment]
I had the same issue yesterday and now all but a few of my XLM have been sent out of my wallet to an unknown address as there is no transaction history between public addresses and it is not in the wallet I was trying to send it too.

**Comment by ToadTime** [comment]
> I had the same issue yesterday and now all but a few of my XLM have been sent out of my wallet to an unknown address as there is no transaction history between public addresses and it is not in the wallet I was trying to send it too.

**Comment by ToadTime** [comment]
You have to use the private key (from this wallet) and use it to pull funds off your old wallet.

**Comment by ToadTime** [comment]
Use "private" key, and when it asks for address I used the address that you sent funds to/with.but you can push and pull transactions. In this case you want to pull the transaction not push (send).
